const menu = [
  {
    id: 1,
    title: "cappuccino",
    category: "breakfast",
    price: 5.99,
    img: "./images/cappuccino.jpg",
    desc: `Just a regular cappuccino. Come on, no need to explain anything, right?`,
  },
  {
    id: 2,
    title: "caesar salad",
    category: "lunch",
    price: 19.99,
    img: "./images/salad.jpg",
    desc: `Tossed salad made of romaine, garlic, anchovies, and croutons and dressed with olive oil, coddled egg, lemon juice, and grated cheese.`,
  },
  {
    id: 3,
    title: "strawberry shake",
    category: "shakes",
    price: 6.99,
    img: "./images/strawberryshake.jpg",
    desc: `Strawberry milkshake: it's creamy, light and refreshing and looks adorably delicious, too, with its cloud of pink fluff. It can be served over cold or warm milk, stirred in or left floating on top.`,
  },
  {
    id: 4,
    title: "carrot cake",
    category: "breakfast",
    price: 9.99,
    img: "./images/carrotcake.jpg",
    desc: `Sweet and moist spice cake, full of cut carrots and toasted nuts, and covered in cream cheese icing.`,
  },
  {
    id: 5,
    title: "pasta al pesto",
    category: "lunch",
    price: 14.99,
    img: "./images/pastapesto.jpg",
    desc: `This-a very good pasta al pesto, 100% italian made mama mia!`,
  },
  {
    id: 6,
    title: "coconut fantasy",
    category: "shakes",
    price: 10.99,
    img: "./images/cocoshake.jpg",
    desc: `Coconut Shake, an absolute tropical delight to taste buds, is prepared by blending toasted coconut, milk and ice cream and sweetened with sugar to taste.`,
  },
  {
    id: 7,
    title: "pancakes",
    category: "breakfast",
    price: 6.99,
    img: "./images/pancakes.jpg",
    desc: `Freshly made pancakes with maple syrup and fruits`,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/burger.jpg",
    desc: `Popular sandwich made from ground meats that are formed into a patty, cooked, and placed between two halves of a bun. Chips included.`,
  },
  {
    id: 9,
    title: "green apples smoothie",
    category: "shakes",
    price: 16.99,
    img: "./images/smoothie.jpg",
    desc: `Refreshing, exhilarating, fresh, energizing, revitalizing, delectable, delightful, luscious, yummy, enticing, fresh, hearty. I am not sure I can come up with enough adjectives to describe how wonderful it is.`,
  },
];
export default menu;
